### ISSUE TITLE
hope support signature generate

### ISSUE THREAD

**Issue by lidongtony** [iamatef/xbogus#2]
Will this repository support the signature algorithm of the signature parameter?

**Comment by iamatef** [comment]
Tests for requests showed that the _signature parameter is not required and only the x-bogus parameter which must be existing and must hold a correct calculated value 

this is at least for endpoints we are depending on right now like a specific tag videos 

Regards,
Atef

**Comment by lidongtony** [comment]
Fine, Thanks your reply @iamatef
